const actions = {
  GET_DATA_JD: 'GET_DATA_JD',
  GET_DATA_JD_SUCCESS: 'GET_DATA_JD_SUCCESS',
  GET_DATA_CANDIDATE: 'GET_DATA_CANDIDATE',
  GET_DATA_CANDIDATE_SUCCESS: 'GET_DATA_CANDIDATE_SUCCESS',
  ADD_DATA_JD: 'ADD_DATA_JD',
  EDIT_DATA_JD: 'EDIT_DATA_JD',
  DELETE_DATA_JD: 'DELETE_DATA_JD',
  ADD_DATA_CANDIDATE: 'ADD_DATA_CANDIDATE',
  PAGINATION_DATA: 'PAGINATION_DATA',
  EDIT_DATA_CANDIDATE: 'EDIT_DATA_CANDIDATE',
  DELETE_DATA_CANDIDATE: 'DELETE_DATA_CANDIDATE',
  REDIRECT_LOGIN_TOKEN_EXP: 'REDIRECT_LOGIN_TOKEN_EXP',
  // Login handler
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
  USER_LOGOUT: 'USER_LOGOUT',
  // Manager user
  GET_LIST_USER: 'GET_LIST_USER',
  GET_LIST_USER_SUCCESS: 'GET_LIST_USER_SUCCESS',
  EDIT_USER: 'EDIT_USER',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  ADD_USER: 'ADD_USER',
  LIST_USER_BLOCK: 'LIST_USER_BLOCK',
  LIST_USER_ALL: 'LIST_USER_ALL',

  // skills
  GET_LIST_SKILL: 'GET_LIST_SKILL',
  GET_LIST_SKILL_SUCCESS: 'GET_LIST_SKILL_SUCCESS',

  // positions
  GET_LIST_POSITION: 'GET_LIST_POSITION',
  GET_LIST_POSITION_SUCCESS: 'GET_LIST_POSITION_SUCCESS',

  // modal
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',

  // address
  GET_LIST_ADDRESS: 'GET_LIST_ADDRESS',
  GET_LIST_ADDRESS_SUCCESS: 'GET_LIST_ADDRESS_SUCCESS',
};
export default actions;
